version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP="true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
     # - data01:/usr/share/elasticsearch/data
       - /var/elasticsearch/data/data01:/usr/share/elasticsearch/data
       - /var/elasticsearch/logs/:/usr/share/elasticsearch/logs
     # - /var/elasticsearch/config:/usr/share/elasticsearch/config/

    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.2
  container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
